### ISSUE TITLE
Replace 0,00 label in expenses by "free"

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#100]
On the home screen list view, add a condition for free items

**Comment by TheBlueBaronx** [comment]
I added this to the home screen - I think there is nothing else to this issue, right @NightmindOfficial ?

**Comment by NightmindOfficial** [comment]
Will check

**Comment by NightmindOfficial** [comment]
Is fixed, but I am mad at your json layout ://
