### ISSUE TITLE
Pressing the "Sign up now!"-button has an error

### ISSUE THREAD

**Issue by SoTBurst** [VICFR1TZ/linum#101]
**Describe the bug**
There is an error when you open the signup lip

**To Reproduce**
1. Be logged out.
2. Press sign up
3. You get the error:

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 3023 pos 16: 'node.parent ==
null || !node.parent!.isPartOfNodeMerging || node.isMergedIntoParent': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:3023:16)
#3      PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1098:24)
#4      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:502:21)
#5      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#6      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#13     _invoke (dart:ui/hooks.dart:151:10)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#15     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Additional context**
For proper automatic testing, we can't have invisible errors.

**Comment by NightmindOfficial** [comment]
Is a regression.

**Comment by NightmindOfficial** [comment]
This issue will be gone when `feature/applock` gets merged into development.

**Comment by TheBlueBaronx** [comment]
What's up with this issue?

**Comment by NightmindOfficial** [comment]
Good question - advise to close the issue for now as it has not occurred within the last two months. We can reopen it anytime it becomes a problem again.
