### ISSUE TITLE
Swipe left and right to change between Expenses, Income and Transaction

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#103]
**Is your feature request related to a problem? Please describe.**
Right now this in only achievable by clicking on the fields

**Describe the solution you'd like**
Swipe left and right to change it

**Comment by TheBlueBaronx** [comment]
@NightmindOfficial Könntest du einmal auf einem echten Device testen?

**Comment by NightmindOfficial** [comment]
Sure

**Comment by NightmindOfficial** [comment]
Also

1. Die Swipe-Richtung musst du noch inverten (swipe nach links bewegt cursor nach rechts), 
2. Die Geste sollte man auf dem gesamten Screen machen können, sonst ist das ganze Feature nicht so sinnvoll (dann könntest du oben nämlich auch einfach tippen)
