### ISSUE TITLE
Category: Subcategories, custom categories and more

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#129]
**Describe the solution you'd like**
The categories need a big rework. This includes: 
- The option for a user to choose between categories and subcategories
- To add custom categories as well as to edit the preinstalled categories
- Categories need to have the following features that all need to be editable: Name, Icon, Color and the state whether it is a category or subcategory. Also we need to give the user the option to delete all categories and subcategories

The following things need to be changed or added:

**Backend**:
- The option to differentiate between categories and subcategories
- The option to edit and delete categories (preinstalled categories as well as custom categories)

**Frontend**:
- An action lip in the enter screen with the possibility to differentiate and select between categories and subcategories 
- An option to add new categories with all respective features (settings-screen)
- An option to delete categories (settings-screen)

**Comment by NightmindOfficial** [comment]
Since we have implemented a WIDE range of changes to this feature, it might probably make the most sense to rewrite this.
