### ISSUE TITLE
Statistic Screen

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#143]
**Describe the solution you'd like**
A statistic screen that shows all relevant statistics about your spendings 

**Context**

**Backend:** 
Make following data accessible: 
- Spending per month 
- Spending per month per category 
- Transactions per category and subcategory per month 

**Frontend:**
- See Figma/Screenshot
<img width="546" alt="Bildschirmfoto 2022-04-12 um 23 13 15" src="https://user-images.githubusercontent.com/82233540/163055560-93b36f55-87a4-4894-bf63-432ad2d076bd.png">
s

**Comment by NightmindOfficial** [comment]
Closing this as a response to recent priority restructuring within the dev team.
