### ISSUE TITLE
"Plus" in the bottom app bar is raised from a SnackBar 

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#144]
**Describe the bug**
Whenever a snackbar is shown, the plus from the bottom app bar is raised above it 
![IMG_1652](https://user-images.githubusercontent.com/82233540/163173813-9f3569d0-706c-4e7f-b57e-2320204e500f.PNG

**Expected behavior**
Should be behind it

**Comment by NightmindOfficial** [comment]
It's not a bug, it's actually a feature, as both Widgets (FloatingButton & SnackBar) must not be covered by anything at any time.

So should **not** be behind it.

**Comment by NightmindOfficial** [comment]
Easy solution: Draw a Toast instead of a snackbar to signal completion of notification setup. @TheBlueBaronx

**Comment by TheBlueBaronx** [comment]
Answered
