### ISSUE TITLE
Add minimum distance in the card in the home screen. 

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#149]
**Is your feature request related to a problem? Please describe.**
This is part of the rework of the card on the home screen. @NightmindOfficial  Please add a minimum distance between the date and the border of the card as well as the income and expense amount and the border of the card because otherwise, it can get too stretchy on some screens.

![Screenshot_1651010697](https://user-images.githubusercontent.com/82233540/165400551-5c607b6e-0b50-49d7-9ac3-2ba1d9253bea.png)

**Comment by NightmindOfficial** [comment]
Why does the card even scale? It is supposed to be fixed!
