### ISSUE TITLE
Settings-Screen not usable after entering Enter-Screen or reinstalling the app

### ISSUE THREAD

**Issue by damattl** [VICFR1TZ/linum#150]
After the Enter-Screen is opened in the app the Settings-Screen does not react to changes anymore.
The same is true for uninstalling the app and the logging in again for the first time.

Both bugs disappear when restarting the app.

**Comment by NightmindOfficial** [comment]
@damattl what is the status on this one? I'd consider this critical.

**Comment by damattl** [comment]
Solved on the 150 branch, not sure if the fix broke something else, but so far there are no more problems.

**Comment by NightmindOfficial** [comment]
OK - marked this as solved for now.
