### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by damattl** [VICFR1TZ/linum#152]
**Describe the solution you'd like**
Use Google Analytics to better understand how the app is being used.

**Backend**
- Add Google Analytics for Firebase plugin

**Frontend**
- Track Buttons
- Track Gestures
- Track most used functions

**Comment by NightmindOfficial** [comment]
Is technically fixed, will be closed when @damattl writes "fix #152"

**Comment by NightmindOfficial** [comment]
@damattl did you write "fix #152", or is this still an issue?

**Comment by damattl** [comment]
We did stale this feature a couple months ago, check out the no-merge branch

**Comment by NightmindOfficial** [comment]
The entire project has been stale for about one year. Will close this as (currently) not planned.
