### ISSUE TITLE
Filter Screen

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#154]
**Is your feature request related to a problem? Please describe.**
Currently the "filter-screen" is located in the budgeting screen and has no functionality. But we want it to be an own screen that:

- is a sub-page to the main screen that is shown whenever you click on "more"
- has many different filter options e.g. by category, repeating/non repeating etc.

**Comment by NightmindOfficial** [comment]
Already part of Linear (own project).
