### ISSUE TITLE
Budgeting Screen

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#156]
**Is your feature request related to a problem? Please describe.**
Users should have the option to set a budget and have a look at whether their income/expenses match this budget. This screen is located at the budgeting screen
<img width="248" alt="Bildschirmfoto 2022-05-04 um 19 52 23" src="https://user-images.githubusercontent.com/82233540/166749133-ca5169fa-551b-4c21-8458-9a6053dc5a9f.png">
<img width="243" alt="Bildschirmfoto 2022-05-04 um 19 52 42" src="https://user-images.githubusercontent.com/82233540/166749181-03e83ef4-b7ba-4f8e-9088-9040670cdc8e.png">
.

**Comment by NightmindOfficial** [comment]
Imported as own Linear project. closing this here.
