### ISSUE TITLE
PIN feature not working correctly

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#181]
Talk to @damattl or @NightmindOfficial , they know but were too lazy to describe the problem on 02:54 AM here.

**Comment by damattl** [comment]
Temporarily solved with hotfix/pinlock-bypass, changing priority

**Comment by damattl** [comment]
Lock Screen shows up, after the HomeScreen renders -> not a very nice User experience
Should perhaps be resolved with the Routing Update
