### ISSUE TITLE
[LINUM-27] Broken Responsive Design on HomeScreenCard Backside

### ISSUE THREAD

**Issue by damattl** [VICFR1TZ/linum#264]
<sub>From [SyncLinear.com](https://synclinear.com) | [LINUM-27](https://linear.app/invest-it/issue/LINUM-27/broken-responsive-design-on-homescreencard-backside)</sub>

**Comment by NightmindOfficial** [comment]
Won't fix for now. Reason: With the switch to MD3 the entire design system of the app will be fucked anyways, so higher efforts into improving the app design-wise are not really efficient right now. Will look into this as soon as the MD3 integration is completed.

**Comment by NightmindOfficial** [comment]
Test.

**Comment by NightmindOfficial** [comment]
Another test.

**Comment by NightmindOfficial** [comment]
Third test.

**Comment by NightmindOfficial** [comment]
FOURTH TEST FFS

**Comment by NightmindOfficial** [comment]
FIFTH TEST AAAAAAAHHHH

**Comment by damattl** [comment]
Hallo Welt
