### ISSUE TITLE
[LINUM-182] [LINUM-183] Language Switcher does not work

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#287]
Language Switching from System Lang to manual selection is not working. This is probably an issue that extends over the entire settings screen, as the PIN feature also does not work (see #284 ).

Tested on Emulator: Pixel 6 with Android 13.

<sub>[LINUM-183](https://linear.app/invest-it/issue/LINUM-183/language-switcher-does-not-work)</sub>

**Comment by damattl** [comment]
Can't reproduce on iOS

**Comment by NightmindOfficial** [comment]
Cannot reproduce at home either. In any case, at home there is another issue:

The app restarts to home screen instead of settings screen.

**Comment by NightmindOfficial** [comment]
Advise that we are testing this on as many devices as possible.

Could be Android 14 specific

**Comment by damattl** [comment]
This is wanted behaviour at the moment, because the whole App has to restart. We could however design the transition to be more gracefully

**Comment by NightmindOfficial** [comment]
Isn't this a step backwards? I know that there was instant language switching in earlier versions. Is this completely off the table with the new version?

**Comment by damattl** [comment]
Might have found a quick workaround

**Comment by damattl** [comment]
Transition is still ugly
