### ISSUE TITLE
[LINUM-204] Changing Currency does not work

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#297]
Similar to Issue #296, trying to change the currency in the settings screen opens the actionDialogue, but is not saved. Probably is caused by improper provider setup.

Device: OnePlus 9 Pro 5G, Android 4 (Upside Down Cake, API34)
Version: 1.2.3 (20)

We should fix this fast, at least before we merge to prod! @damattl 

<sub>[LINUM-204](https://linear.app/invest-it/issue/LINUM-204/changing-currency-does-not-work)</sub>

**Comment by damattl** [comment]
Hm komisch - das hat bei mir gestern noch funktioniert
