### ISSUE TITLE
[LINUM-215] Contracts Screen partially broken

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#303]
e.g. shows expenses in the income category in the ListView, might need heavy overhaul

<sub>[LINUM-215](https://linear.app/invest-it/issue/LINUM-215/contracts-screen-partially-broken)</sub>

**Comment by damattl** [comment]
Cannot reproduce on new accounts @otis.mohr

**Comment by NightmindOfficial** [comment]
Yeah, might have something to do with old accounts only. How to proceed @shogunpurple.mayer ?
