### ISSUE TITLE
Repeatable Transactions - Option: "Monthly" 

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#66]
We should have two options: 

1. Option: Transaction repeats on the first of each month
2. Option: Transaction repeats monthly on the day the first transaction is set (e.g. the 8th of...)

Backend: 
- [x] Build a function that repeats the transaction month by month and that takes leap years etc. into consideration

Frontend: 
- [x] Restructure the bottomList to an Action Lip
- [x] Implement the two options

**Comment by SoTBurst** [comment]
For now it just uses the date chosen as date.
