### ISSUE TITLE
Edit repeatable transactions

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#68]
Required functionality: 

- [ ] Currently whenever you change the category, name etc. only the transaction edited is changed and not all the repeated transactions - we need to give the user the option to do either one

**Comment by SoTBurst** [comment]
This on porpoise. For better visibility, we should add the screen with all repeatables for that. 
Other approaches are fine, but this is definitely 1.1. update

**Comment by NightmindOfficial** [comment]
Are you working on this rn @SoTBurst ? If yes, pls assign this task so I don't accidentally purge it in my next GH cleanup routine.
