### ISSUE TITLE
Push-Notifications

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#72]
**Goal**
The goal is to remind the user to use the app and as a consequence gain more MAUs

**Required Features**

Settings Screen:
- The option to deactivate / manage all the notificiations (standard should be that the user receives notifications)

General:
- Daily reminder to add spendings to the app

**Future**
In the future there should be many more possibilities for notifications e.g. notifications that show the current situation of the monthly budget - please make sure to have this in mind when implementing the functionality in the settings screen

**Comment by NightmindOfficial** [comment]
Same here - pls remember to assign yourself if you're working on something

**Comment by NightmindOfficial** [comment]
Added this as a whole project in Linear. Closing the original issue here.
