### ISSUE TITLE
Improve the "balance card" on the home screen

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#73]
**Is your feature request related to a problem? Please describe.**
Currently the user can switch between the different months by swiping left and right on the balance card in the home screen which is indicated to the user through two small arrows. This needs to be changed and the balance card needs also needs to be improved in its design.  

**Describe the solution you'd like**
tbd

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by NightmindOfficial** [comment]
This issue has already been fixed / implemented in the recent 1.1.0+8 release.
