### ISSUE TITLE
Amount Input buggy

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#86]
**Describe the bug**
Amount Input is only displayed partially

**To Reproduce**
1. Go to Enter Screen
2. See issue

**Screenshots**
![IMG-20220313-WA0026.jpg](https://user-images.githubusercontent.com/62300272/158079717-1e7815dd-649f-4322-8de2-765363b57c35.jpg)

**About your phone (please complete the following information):**
 - Device: iPhone 12
 VERSION 1.0.4

**Additional context**

**Comment by TheBlueBaronx** [comment]
On my emulator this is not the case, see screenshot below
<img width="393" alt="Bildschirmfoto 2022-03-16 um 18 49 09" src="https://user-images.githubusercontent.com/82233540/158654950-e68cdaac-69f5-4a9f-bbd1-30dd8839d011.png">

**Comment by NightmindOfficial** [comment]
We were not able to address this because it works on all possible scenarios reproducible by us. We were also able to rule out common issue sources.
