### ISSUE TITLE
Resolve PIN issue on creating new accounts

### ISSUE THREAD

**Issue by NightmindOfficial** [VICFR1TZ/linum#97]
Reproduction Steps:

1. Create Account A -> Activate PIN lock and set PIN (e.g. "1234")
2. Log out
3. Create another Account B -> Verify Mail
4. Log in with B

After logging in for the first time, B will be presented with a PIN Query. The code for account A, however, does not work.

**Comment by SoTBurst** [comment]
Now we have the problem, that you can see the pin field for a split second

**Comment by NightmindOfficial** [comment]
@SoTBurst I had to destroy our temporary solution for the PIN lock because you could not set/change PIN number with the screen getting reset to 0. But I found the root cause of this issue. See the image below:

![grafik](https://user-images.githubusercontent.com/62300272/158711560-74589be1-1633-43cf-abfd-286e4c0b6da1.png)

When a new user is created, the _initialIsPinActive is NOT called early enough!
the _initialIsPinActive() is the Function that logs the "PIN lock is (NOT) ACTIVE for {email} to the debug console.
However, the if loop of layout screen is triggered with the old status before the refresh, so the PIN lock is already being displayed before the _isPinActive updates. How do we address this?

**Comment by NightmindOfficial** [comment]
This is even heavier, the email is not even loaded and just uses the default value "Loading..."
--> This means that _lastEmailStillLoading was true when the if loop was executed
---> This in turn means that we have to await the status update of mail - unsure on how to implement this. @SoTBurst any advice?

![grafik](https://user-images.githubusercontent.com/62300272/158714199-9fd915a2-0096-4f25-91a9-6c2edcdcfee6.png)
