### ISSUE TITLE
NavBar too small on some devices

### ISSUE THREAD

**Issue by TheBlueBaronx** [VICFR1TZ/linum#98]
**Describe the bug**
On some devices (e.g. Nexus 5 or iPhone 12) the NavBar and the Text was too small

**Expected behavior**
NavBar should have the same height on all devices

**Comment by NightmindOfficial** [comment]
Why can't we address this? This is just about setting a fixed height for the navbar on all devices, or am I mistaken?

**Comment by TheBlueBaronx** [comment]
I tried it on said device and I could not see the mistake - but you can try to adjust it in bottom_app_bar.dart in line 92 @NightmindOfficial

**Comment by NightmindOfficial** [comment]
Somehow we lost the fix after the big merge. Reopening this.
